name: semaphore

base: core22

version: 2.8.77

license: MIT

summary: Modern UI for Ansible

architectures:
- build-on: amd64
- build-on: arm64

description: |
  Ansible Semaphore is beautiful web interface for running Ansible playbooks.
  If your project has grown and deploying from the terminal is no longer for you then Ansible Semaphore is what you need.

grade: stable

confinement: strict

apps:
  semaphored:
    command: bin/snapcraft-preload $SNAP/semaphored
    daemon: simple
    plugs:
    - network-bind
    - network
    - ssh-keys
    - mount-observe

  semaphore:
    command: bin/snapcraft-preload $SNAP/semaphore
    environment:
      SEMAPHORE_CONFIG_PATH: $SNAP_USER_COMMON/config.json
    plugs:
    - network-bind
    - network
    - ssh-keys
    - mount-observe


parts:
  snapcraft-preload:
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=
    source: https://github.com/sergiusens/snapcraft-preload.git
    build-packages:
    - on amd64:
      - gcc-multilib
      - g++-multilib
    stage-packages:
    - on amd64:
      - lib32stdc++6
          
  semaphore:
    plugin: dump
    source:
    - on arm64: https://github.com/ansible-semaphore/semaphore/releases/download/v2.8.77/semaphore_2.8.77_linux_arm64.deb
    - else:
      - on amd64: https://github.com/ansible-semaphore/semaphore/releases/download/v2.8.77/semaphore_2.8.77_linux_amd64.deb
      - else fail
    source-type: deb

  semaphored:
    plugin: nil
    source: ./bin
    source-type: local
    override-build: |
      chmod +x semaphored
      cp semaphored $SNAPCRAFT_PART_INSTALL/semaphored
      chmod +x semaphore
      cp semaphore $SNAPCRAFT_PART_INSTALL/semaphore
    stage-packages:
    - git
    - openssh-client
    - sshpass
    - rsync

  ansible:
    plugin: python
    source: .
    build-packages:
    - python3-virtualenv
    - python3-venv
    - python3-dev
    stage-packages:
    - python3
    - python3-venv
    - python3-virtualenv
    python-packages:
    - setuptools
    override-build: |
      virtualenv ansible_env
      export PATH=ansible_env/bin:$PATH
      CRYPTOGRAPHY_DONT_BUILD_RUST=1
      pip3 install --upgrade pip
      pip3 install setuptools_rust wheel setuptools botocore boto3
      pip3 install ansible
      tar cfz ansible_env.tar.gz ansible_env
      cp ansible_env.tar.gz $SNAPCRAFT_PART_INSTALL