name: semaphore

base: core20

version: 2.13.1

license: MIT

summary: Modern UI and powerful API for Ansible, Terraform and other DevOps tools

architectures:
- build-on: amd64
- build-on: arm64

description: |
  Semaphore is beautiful web interface for running Ansible playbooks.
  If your project has grown and deploying from the terminal is no longer for you then Semaphore is what you need.

grade: stable

confinement: classic

apps:
  semaphored:
    command: $SNAP/bin/semaphore server
    environment:
      SEMAPHORE_CONFIG_PATH: $SNAP_USER_COMMON/config.json
      SNAPCRAFT_PRELOAD_REDIRECT_ONLY_SHM: 1
    daemon: simple

  semaphore:
    command: $SNAP/bin/semaphore
    environment:
      SEMAPHORE_CONFIG_PATH: $SNAP_USER_COMMON/config.json
      SNAPCRAFT_PRELOAD_REDIRECT_ONLY_SHM: 1


parts:
  semaphore:
    plugin: nil
    source: 
      - on amd64: https://github.com/semaphoreui/semaphore/releases/download/v2.13.1/semaphore_2.13.1_linux_amd64.tar.gz
      - on arm64: https://github.com/semaphoreui/semaphore/releases/download/v2.13.1/semaphore_2.13.1_linux_arm64.tar.gz
    source-type: tar
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp terraform $SNAPCRAFT_PART_INSTALL/bin/