name: semaphore
base: core18
version: 2.7.1
summary: Modern UI for Ansible
description: |
  Ansible Semaphore is beautiful web interface for running Ansible playbooks.
  If your project has grown and deploying from the terminal is no longer for you then Ansible Semaphore is what you need.

grade: devel
confinement: strict
architectures: [arm64}]

apps:
  semaphored:
    command: semaphored
    daemon: simple
    plugs:
      - network-bind

  semaphore:
    command: semaphore
    plugs:
      - network-bind
      - network

parts:
  semaphore:
    plugin: dump
    source:
      - on amd64: https://github.com/ansible-semaphore/semaphore/releases/download/v2.7.1/semaphore_2.7.1_linux_amd64.deb
      - else: https://github.com/ansible-semaphore/semaphore/releases/download/v2.7.1/semaphore_2.7.1_linux_arm64.deb
    source-type: deb

  semaphored:
    plugin: nil
    source: ./bin
    source-type: local
    override-build: |
      chmod +x semaphored
      cp semaphored $SNAPCRAFT_PART_INSTALL/semaphored