name: semaphore
base: core18
version: 2.7.2
summary: Modern UI for Ansible
description: |
  Ansible Semaphore is beautiful web interface for running Ansible playbooks.
  If your project has grown and deploying from the terminal is no longer for you then Ansible Semaphore is what you need.
grade: devel
confinement: devmode
architectures:
  - amd64
apps:
  semaphored:
    command: semaphored
    daemon: simple
    plugs:
      - network-bind
  semaphore:
    command: semaphore -config $SNAP_USER_COMMON/config.json
    plugs:
      - network-bind
      - network
parts:
  semaphore:
    plugin: dump
    source:
      - on arm64: https://github.com/ansible-semaphore/semaphore/releases/download/v2.7.2/semaphore_2.7.2_linux_arm64.deb
      - else:
        - on amd64: https://github.com/ansible-semaphore/semaphore/releases/download/v2.7.2/semaphore_2.7.2_linux_amd64.deb
        - else fail
    source-type: deb
    stage-packages:
      - git

  semaphored:
    plugin: nil
    source: ./bin
    source-type: local
    override-build: |
      chmod +x semaphored
      cp semaphored $SNAPCRAFT_PART_INSTALL/semaphored
    stage-packages:
      - git

  ansible:
    plugin: python
    source: .
    build-packages:
      - python3-pip
      - python3.6-venv
      - python3-dev
    stage-packages:
      - python3-pip
      - python3.6-venv
      - python3-dev
    override-build: |
      python3 -m venv ansible_env

      export PATH=ansible_env/bin:$PATH

      export CRYPTOGRAPHY_DONT_BUILD_RUST=1
      
      pip3 install wheel
      
      pip3 install setuptools
      
      pip3 install ansible

      tar cfz ansible_env.tar.gz ansible_env

      cp ansible_env.tar.gz $SNAPCRAFT_PART_INSTALL