name: semaphore

base: core18

version: 2.8.33

license: MIT

summary: Modern UI for Ansible

description: |
  Ansible Semaphore is beautiful web interface for running Ansible playbooks.
  If your project has grown and deploying from the terminal is no longer for you then Ansible Semaphore is what you need.

grade: stable

confinement: strict

apps:
  semaphored:
    command: bin/snapcraft-preload $SNAP/semaphored
    daemon: simple
    plugs:
      - network-bind
      - network
      - ssh-keys
      - mount-observe

  semaphore:
    command: bin/snapcraft-preload $SNAP/semaphore
    environment:
      SEMAPHORE_CONFIG_PATH: $SNAP_USER_COMMON/config.json
    plugs:
      - network-bind
      - network
      - ssh-keys
      - mount-observe


parts:
  snapcraft-preload:
      source: https://github.com/sergiusens/snapcraft-preload.git
      plugin: cmake
      build-packages:
        - on amd64:
          - gcc-multilib
          - g++-multilib
          
  semaphore:
    plugin: dump
    source:
      - on arm64: https://github.com/ansible-semaphore/semaphore/releases/download/v2.8.33/semaphore_2.8.33_linux_arm64.deb
      - else:
        - on amd64: https://github.com/ansible-semaphore/semaphore/releases/download/v2.8.33/semaphore_2.8.33_linux_amd64.deb
        - else fail
    source-type: deb

  semaphored:
    plugin: nil
    source: ./bin
    source-type: local
    override-build: |
      chmod +x semaphored
      cp semaphored $SNAPCRAFT_PART_INSTALL/semaphored
      chmod +x semaphore
      cp semaphore $SNAPCRAFT_PART_INSTALL/semaphore
    stage-packages:
      - git
      - openssh-client
      - sshpass

  ansible:
    plugin: python
    source: .
    build-packages:
      - python3-venv
      - python3-dev
    stage-packages:
      - python3-venv
    override-build: |
      python3 -m venv ansible_env
      export PATH=ansible_env/bin:$PATH
      CRYPTOGRAPHY_DONT_BUILD_RUST=1
      pip3 install --upgrade pip
      pip3 install setuptools_rust wheel setuptools botocore boto3
      pip3 install ansible
      tar cfz ansible_env.tar.gz ansible_env
      cp ansible_env.tar.gz $SNAPCRAFT_PART_INSTALL